---
- name: Install and start Apache
  hosts: all
  become: yes
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present

  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Restart Apache
    service:
      name: apache2
      state: restarted