apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-rolebinding
  namespace: default # Change this to your desired namespace
subjects:
  - kind: ServiceAccount
    name: helm-service-account # Change this to the service account or user you want to grant permissions to
    namespace: default # Change this to the namespace of the service account
roleRef:
  kind: Role
  name: helm-role
  apiGroup: rbac.authorization.k8s.io


